import matplotlib.pyplot as plt
import networkx as nx

G = nx.Graph()


G.add_edge('Uthai Thani',"Chai Nat",weight=26)
G.add_edge("Uthai Thani",'Nakhon Sawan',weight=43)
G.add_edge('Chai Nat',"Nakhon Sawan",weight=62)
G.add_edge('Nakhon Sawan',"Sing Buri",weight=100)
G.add_edge('Chai Nat',"Sing Buri",weight=57)
G.add_edge('Nakhon Sawan',"Lop Buri",weight=151)
G.add_edge("Lop Buri",'Sing Buri',weight=32)
G.add_edge('Chai Nat',"Suphan Buri",weight=101)
G.add_edge('Ang Thong',"Suphan Buri",weight=44)
G.add_edge('Ang Thong',"Sing Buri",weight=40)
G.add_edge('Ang Thong',"Lop Buri",weight=42)
G.add_edge('Saraburi',"Lop Buri",weight=47)
G.add_edge('Saraburi',"Nakhon Nayok",weight=58)
G.add_edge('Saraburi',"Pathum Thani",weight=85)
G.add_edge('Saraburi',"Ayutthaya",weight=69)
G.add_edge('Ayutthaya',"Ang Thong",weight=39)
G.add_edge('Ayutthaya',"Suphan Buri",weight=64)
G.add_edge('Ayutthaya',"Pathum Thani",weight=50)
G.add_edge('Ayutthaya',"Nakhon Pathom",weight=32)
G.add_edge('Ayutthaya',"Nonthaburi",weight=75)
G.add_edge('Pathum Thani',"Nakhon Nayok",weight=117)
G.add_edge('Pathum Thani',"Nonthaburi",weight=27)
G.add_edge('Pathum Thani',"Bangkok",weight=42)
G.add_edge('Suphan Buri',"Kanchanaburi",weight=98)
G.add_edge('Suphan Buri',"Nakhon Pathom",weight=97)
G.add_edge('Nakhon Nayok',"Prachin Buri",weight=20)
G.add_edge('Nakhon Nayok',"Chachoengsao",weight=75)
G.add_edge('Chachoengsao',"Prachin Buri",weight=74)
G.add_edge('Chachoengsao',"Bangkok",weight=85)
G.add_edge('Chachoengsao',"Chon Buri",weight=50)
G.add_edge('Kanchanaburi',"Nakhon Pathom",weight=67)
G.add_edge('Kanchanaburi',"Ratchaburi",weight=81)
G.add_edge('Nakhon Pathom',"Nonthaburi",weight=64)
G.add_edge('Nakhon Pathom',"Bangkok",weight=57)
G.add_edge('Nakhon Pathom',"Samut Sakhon",weight=67)
G.add_edge('Nakhon Pathom',"Ratchaburi",weight=48)
G.add_edge('Bangkok',"Nonthaburi",weight=22)
G.add_edge('Bangkok',"Prachin Buri",weight=145)
G.add_edge('Bangkok',"Samut Sakhon",weight=38)
G.add_edge('Bangkok',"Samut Prakan",weight=26)
G.add_edge('Chon Buri',"Samut Prakan",weight=70)
G.add_edge('Samut Sakhon',"Ratchaburi",weight=67)
G.add_edge('Samut Sakhon',"Samut Songkhram",weight=38)
G.add_edge('Ratchaburi',"Samut Songkhram",weight=35)
G.add_edge('Phetchaburi',"Ratchaburi",weight=58)
G.add_edge('Phetchaburi',"Samut Songkhram",weight=57)

edge_labels = nx.get_edge_attributes(G,'weight')
print(edge_labels)

pos = nx.spring_layout(G)
nx.draw(G,pos ,with_labels=True,font_color="black",font_size="5",node_size= 2000)
nx.draw_networkx_edge_labels(G,pos,edge_labels=edge_labels)
plt.show()